#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if and .Values.components.prometheus }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.prometheus.name }}-operator
  namespace: {{ .Values.install_namespace }} 
spec:
  channel: {{ .Values.prometheus.channel }}
  installPlanApproval: {{ .Values.prometheus.approval | default .Values.approval }}  
  source: {{ .Values.prometheus.source }}
  sourceNamespace: {{ .Values.olm_namespace }}
  name: {{ .Values.prometheus.name }}
  config:
    {{- if .Values.tolerations }}
    tolerations:
{{ toYaml .Values.tolerations | indent 4 }}
    {{- end }}
    resources: {{ include "subscription.prometheusResources" . }}
    {{- if .Values.prometheus.config.env }}
    env:
    {{- toYaml .Values.prometheus.config.env | nindent 4 }}
    {{- end }}
    {{- if .Values.prometheus.config.envFrom }}
    envFrom:
    {{- toYaml .Values.prometheus.config.envFrom | nindent 4 }}
    {{- end }}
{{- end }}
